---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-event-emitted
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-event-emitted
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-event-emitted
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
