---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venaficonnection
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["jetstack.io"]
    resources:
      - venaficonnections
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venaficonnection
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venaficonnection
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-cluster-viewer
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-node-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-node-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-node-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-secret-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-secret-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-cert-manager-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-cert-manager-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-cert-manager-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-googlecas-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cas-issuer.jetstack.io"]
    resources:
      - googlecasissuers
      - googlecasclusterissuers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-googlecas-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-googlecas-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-awspca-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["awspca.cert-manager.io"]
    resources:
      - awspcaissuers
      - awspcaclusterissuers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-awspca-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-awspca-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-webhook-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-webhook-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-webhook-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-openshift-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*.openshift.io"]
    resources:
      - routes
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-openshift-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-openshift-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-istio-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["networking.istio.io"]
    resources:
      - virtualservices
      - gateways
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-istio-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-istio-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venafi-enhanced-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["jetstack.io"]
    resources:
      - venafiissuers
      - venaficlusterissuers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venafi-enhanced-reader
  labels:
    {{- include "venafi-kubernetes-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "venafi-kubernetes-agent.fullname" . }}-venafi-enhanced-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "venafi-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
