issues:
  exclude-rules:
    - linters:
        - staticcheck
        - errcheck
        - unconvert
        - unparam
        - dupword
        - gosimple
        - nilerr
        - nilnil

        # TODO(mael): add the following linters one by one and fix the issues
        # they report. I didn't have time to do that when I migrated to
        # makefile-modules.
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose
        - contextcheck
        - decorder
        - dogsled
        - dupword
        - durationcheck
        - errcheck
        - errchkjson
        - errname
        - execinquery
        - exhaustive
        - exportloopref
        - forbidigo
        - gci
        - ginkgolinter
        - gocheckcompilerdirectives
        - gochecksumtype
        - gocritic
        - gofmt
        - goheader
        - goprintffuncname
        - gosec
        - gosimple
        - gosmopolitan
        - govet
        - grouper
        - importas
        - ineffassign
        - interfacebloat
        - loggercheck
        - makezero
        - mirror
        - misspell
        - musttag
        - nakedret
        - nilerr
        - nilnil
        - noctx
        - nosprintfhostport
        - predeclared
        - promlinter
        - protogetter
        - reassign
        - sloglint
        - staticcheck
        - tagalign
        - tenv
        - testableexamples
        - typecheck
        - unconvert
        - unparam
        - unused
        - usestdlibvars
        - wastedassign
      text: ".*"
linters:
  # Explicitly define all enabled linters
  disable-all: true
  enable: []
linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/jetstack/jetstack-secure) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
