schedule: "* * * * *"
token: "###AUTH_TOKEN###"
endpoint:
  protocol: http
  host: localhost:3000
  path: /api/v1/datareadings
data-gatherers:
- name: "k8s/pods"
  kind: "k8s"
  config:
    resource-type:
      resource: pods
      version: v1
