name: 'Setup repo access'
description: 'Setups authenticate to GitHub repos'
inputs:
  DEPLOY_KEY_READ_VENAFI_CONNECTION_LIB:
    required: true
    description: "DEPLOY_KEY_READ_VENAFI_CONNECTION_LIB secret"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Configure jetstack/venafi-connection-lib repo pull access
      shell: bash
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        
        echo "${{ inputs.DEPLOY_KEY_READ_VENAFI_CONNECTION_LIB }}" > ~/.ssh/venafi_connection_lib_id
        chmod 600 ~/.ssh/venafi_connection_lib_id

        cat <<EOT >> ~/.ssh/config          
        Host venafi-connection-lib.github.com
        HostName github.com
        IdentityFile ~/.ssh/venafi_connection_lib_id
        IdentitiesOnly yes
        EOT
        
        cat <<EOT >> ~/.gitconfig
        [url "git@venafi-connection-lib.github.com:jetstack/venafi-connection-lib"]
          insteadOf = https://github.com/jetstack/venafi-connection-lib
        EOT

        echo "GOPRIVATE=github.com/jetstack/venafi-connection-lib" >> $GITHUB_ENV
