apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discovery-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
data:
  config.yaml: |-
    cluster_name: {{ required "config.clusterName is required" .Values.config.clusterName | quote }}
    cluster_description: {{ .Values.config.clusterDescription | quote }}
    {{- if .Values.config.claimableCerts }}
    claimable_certs: true
    {{- end }}
    period: {{ .Values.config.period | quote }}
    {{- with .Values.config.excludeAnnotationKeysRegex }}
    exclude-annotation-keys-regex:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with .Values.config.excludeLabelKeysRegex }}
    exclude-label-keys-regex:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    data-gatherers:
    - kind: k8s-discovery
      name: k8s-discovery
    - kind: k8s-dynamic
      name: k8s/secrets
      config:
        resource-type:
          version: v1
          resource: secrets
        field-selectors:
        - type!=kubernetes.io/dockercfg
        - type!=kubernetes.io/dockerconfigjson
        - type!=bootstrap.kubernetes.io/token
        - type!=helm.sh/release.v1
    - kind: k8s-dynamic
      name: k8s/jobs
      config:
        resource-type:
          version: v1
          group: batch
          resource: jobs
    - kind: k8s-dynamic
      name: k8s/cronjobs
      config:
        resource-type:
          version: v1
          group: batch
          resource: cronjobs
    - kind: k8s-dynamic
      name: k8s/deployments
      config:
        resource-type:
          version: v1
          group: apps
          resource: deployments
    - kind: k8s-dynamic
      name: k8s/statefulsets
      config:
        resource-type:
          version: v1
          group: apps
          resource: statefulsets
    - kind: k8s-dynamic
      name: k8s/daemonsets
      config:
        resource-type:
          version: v1
          group: apps
          resource: daemonsets
    - kind: k8s-dynamic
      name: k8s/pods
      config:
        resource-type:
          version: v1
          resource: pods
    - kind: "k8s-dynamic"
      name: "k8s/namespaces"
      config:
        resource-type:
          resource: namespaces
          version: v1
    # gather services for pod readiness probe rules
    - kind: "k8s-dynamic"
      name: "k8s/services"
      config:
        resource-type:
          resource: services
          version: v1
    - kind: "k8s-dynamic"
      name: "k8s/ingresses"
      config:
        resource-type:
          group: networking.k8s.io
          version: v1
          resource: ingresses
    - kind: "k8s-dynamic"
      name: "k8s/certificates"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: certificates
    - kind: "k8s-dynamic"
      name: "k8s/certificaterequests"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: certificaterequests
    - kind: "k8s-dynamic"
      name: "k8s/issuers"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: issuers
    - kind: "k8s-dynamic"
      name: "k8s/clusterissuers"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: clusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/googlecasissuers"
      config:
        resource-type:
          group: cas-issuer.jetstack.io
          version: v1beta1
          resource: googlecasissuers
    - kind: "k8s-dynamic"
      name: "k8s/googlecasclusterissuers"
      config:
        resource-type:
          group: cas-issuer.jetstack.io
          version: v1beta1
          resource: googlecasclusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/awspcaissuer"
      config:
        resource-type:
          group: awspca.cert-manager.io
          version: v1beta1
          resource: awspcaissuers
    - kind: "k8s-dynamic"
      name: "k8s/awspcaclusterissuers"
      config:
        resource-type:
          group: awspca.cert-manager.io
          version: v1beta1
          resource: awspcaclusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/mutatingwebhookconfigurations"
      config:
        resource-type:
          group: admissionregistration.k8s.io
          version: v1
          resource: mutatingwebhookconfigurations
    - kind: "k8s-dynamic"
      name: "k8s/validatingwebhookconfigurations"
      config:
        resource-type:
          group: admissionregistration.k8s.io
          version: v1
          resource: validatingwebhookconfigurations
    - kind: "k8s-dynamic"
      name: "k8s/gateways"
      config:
        resource-type:
          group: networking.istio.io
          version: v1alpha3
          resource: gateways
    - kind: "k8s-dynamic"
      name: "k8s/virtualservices"
      config:
        resource-type:
          group: networking.istio.io
          version: v1alpha3
          resource: virtualservices
    - kind: "k8s-dynamic"
      name: "k8s/routes"
      config:
        resource-type:
          version: v1
          group: route.openshift.io
          resource: routes
    - kind: "k8s-dynamic"
      name: "k8s/venaficonnections"
      config:
        resource-type:
          group: jetstack.io
          version: v1alpha1
          resource: venaficonnections
    - kind: "k8s-dynamic"
      name: "k8s/venaficlusterissuers"
      config:
        resource-type:
          group: jetstack.io
          version: v1alpha1
          resource: venaficlusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/venafiissuers"
      config:
        resource-type:
          group: jetstack.io
          version: v1alpha1
          resource: venafiissuers
    - kind: "k8s-dynamic"
      name: "k8s/fireflyissuers"
      config:
        resource-type:
          group: firefly.venafi.com
          version: v1
          resource: issuers
    - kind: "k8s-dynamic"
      name: "k8s/stepissuers"
      config:
        resource-type:
          group: certmanager.step.sm
          version: v1beta1
          resource: stepissuers
    - kind: "k8s-dynamic"
      name: "k8s/stepclusterissuers"
      config:
        resource-type:
          group: certmanager.step.sm
          version: v1beta1
          resource: stepclusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/originissuers"
      config:
        resource-type:
          group: cert-manager.k8s.cloudflare.com
          version: v1
          resource: originissuers
    - kind: "k8s-dynamic"
      name: "k8s/clusteroriginissuers"
      config:
        resource-type:
          group: cert-manager.k8s.cloudflare.com
          version: v1
          resource: clusteroriginissuers
    - kind: "k8s-dynamic"
      name: "k8s/freeipaissuers"
      config:
        resource-type:
          group: certmanager.freeipa.org
          version: v1beta1
          resource: issuers
    - kind: "k8s-dynamic"
      name: "k8s/freeipaclusterissuers"
      config:
        resource-type:
          group: certmanager.freeipa.org
          version: v1beta1
          resource: clusterissuers
    - kind: "k8s-dynamic"
      name: "k8s/ejbcaissuers"
      config:
        resource-type:
          group: ejbca-issuer.keyfactor.com
          version: v1alpha1
          resource: issuers
    - kind: "k8s-dynamic"
      name: "k8s/ejbcaclusterissuers"
      config:
        resource-type:
          group: ejbca-issuer.keyfactor.com
          version: v1alpha1
          resource: clusterissuers
