---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "discovery-agent.fullname" . }}-event-emitted
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-event-emitted
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "discovery-agent.fullname" . }}-event-emitted
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-cluster-viewer
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "discovery-agent.fullname" . }}-secret-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-secret-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "discovery-agent.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "discovery-agent.fullname" . }}-rbac-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
    - roles
    - clusterroles
    - rolebindings
    - clusterrolebindings
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-rbac-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "discovery-agent.fullname" . }}-rbac-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-oidc-discovery
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: system:service-account-issuer-discovery
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "discovery-agent.fullname" . }}-crd-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - cert-manager.io
    - cas-issuer.jetstack.io
    - awspca.cert-manager.io
    - jetstack.io
    - firefly.venafi.com
    - certmanager.step.sm
    - cert-manager.k8s.cloudflare.com
    - certmanager.freeipa.org
    - ejbca-issuer.keyfactor.com
    - networking.istio.io
    - route.openshift.io
    - admissionregistration.k8s.io
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discovery-agent.fullname" . }}-crd-reader
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "discovery-agent.fullname" . }}-crd-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "discovery-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
