# Sample ClusterExternalSecret for e2e testing
# This is a minimal ClusterExternalSecret CR that will be discovered by the agent.
# This is a cluster-scoped resource that can create ExternalSecrets in multiple namespaces.
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: e2e-test-cluster-external-secret
  labels:
    app.kubernetes.io/name: e2e-test
    app.kubernetes.io/component: cluster-external-secret
spec:
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: e2e-test-cluster-secret-store
      kind: ClusterSecretStore
    target:
      name: e2e-test-synced-secret
      creationPolicy: Owner
    data:
    - secretKey: example-key
      remoteRef:
        key: dummy/path/to/secret
        property: password
  namespaceSelector:
    matchLabels:
      environment: test
