---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    {{- include "jetstack-agent.labels" . | nindent 4 }}
data:
  config.yaml: |-
    server: {{ .Values.config.server }}
    organization_id: {{ required "Organisation is a required input value" .Values.config.organisation }}
    cluster_id: {{ required "Cluster is a required input value" .Values.config.cluster }}
    data-gatherers:
    # gather k8s apiserver version information
    - kind: "k8s-discovery"
      name: "k8s-discovery"
    # pods data is used in the pods and application_versions packages
    - kind: "k8s-dynamic"
      name: "k8s/pods"
      config:
        resource-type:
          resource: pods
          version: v1
    # gather services for pod readiness probe rules
    - kind: "k8s-dynamic"
      name: "k8s/services"
      config:
        resource-type:
          resource: services
          version: v1
    # gather higher level resources to ensure data to determine ownership is present
    - kind: "k8s-dynamic"
      name: "k8s/deployments"
      config:
        resource-type:
          version: v1
          resource: deployments
          group: apps
    - kind: "k8s-dynamic"
      name: "k8s/replicasets"
      config:
        resource-type:
          version: v1
          resource: replicasets
          group: apps
    - kind: "k8s-dynamic"
      name: "k8s/statefulsets"
      config:
        resource-type:
          version: v1
          resource: statefulsets
          group: apps
    - kind: "k8s-dynamic"
      name: "k8s/daemonsets"
      config:
        resource-type:
          version: v1
          resource: daemonsets
          group: apps
    - kind: "k8s-dynamic"
      name: "k8s/jobs"
      config:
        resource-type:
          version: v1
          resource: jobs
          group: batch
    - kind: "k8s-dynamic"
      name: "k8s/cronjobs"
      config:
        resource-type:
          version: v1beta1
          resource: cronjobs
          group: batch
    - kind: "k8s-dynamic"
      name: "k8s/ingresses"
      config:
        resource-type:
          group: networking.k8s.io
          version: v1
          resource: ingresses
{{- if or .Values.config.dataGatherers.default (has "secret" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/secrets"
      config:
        resource-type:
          version: v1
          resource: secrets
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "cert-manager" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/certificates"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: certificates
    - kind: "k8s-dynamic"
      name: "k8s/certificaterequests"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: certificaterequests
    - kind: "k8s-dynamic"
      name: "k8s/issuers"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: issuers
    - kind: "k8s-dynamic"
      name: "k8s/clusterissuers"
      config:
        resource-type:
          group: cert-manager.io
          version: v1
          resource: clusterissuers
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "googlecas" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/googlecasissuers"
      config:
        resource-type:
          group: cas-issuer.jetstack.io
          version: v1beta1
          resource: googlecasissuers
    - kind: "k8s-dynamic"
      name: "k8s/googlecasclusterissuers"
      config:
        resource-type:
          group: cas-issuer.jetstack.io
          version: v1beta1
          resource: googlecasclusterissuers
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "awspca" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/awspcaissuer"
      config:
        resource-type:
          group: awspca.cert-manager.io
          version: v1beta1
          resource: awspcaissuers
    - kind: "k8s-dynamic"
      name: "k8s/awspcaclusterissuers"
      config:
        resource-type:
          group: awspca.cert-manager.io
          version: v1beta1
          resource: awspcaclusterissuers
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "webhook" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/mutatingwebhookconfigurations"
      config:
        resource-type:
          group: admissionregistration.k8s.io
          version: v1
          resource: mutatingwebhookconfigurations
    - kind: "k8s-dynamic"
      name: "k8s/validatingwebhookconfigurations"
      config:
        resource-type:
          group: admissionregistration.k8s.io
          version: v1
          resource: validatingwebhookconfigurations
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "istio" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/gateways"
      config:
        resource-type:
          group: networking.istio.io
          version: v1alpha3
          resource: gateways
    - kind: "k8s-dynamic"
      name: "k8s/virtualservices"
      config:
        resource-type:
          group: networking.istio.io
          version: v1alpha3
          resource: virtualservices
{{- end }}
{{- if or .Values.config.dataGatherers.default (has "openshift" .Values.config.dataGatherers.custom) }}
    - kind: "k8s-dynamic"
      name: "k8s/routes"
      config:
        resource-type:
          version: v1
          group: route.openshift.io
          resource: routes
{{- end }}
