---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jetstack-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jetstack-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jetstack-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jetstack-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jetstack-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if  eq .Values.authentication.type "token" }}
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "agent-credentials" .Values.authentication.secretName }}
                  key: {{ default "apitoken" .Values.authentication.secretKey }}
          {{- end }}
          {{- if not (empty .Values.command) }}
          command:
          {{- range .Values.command }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          args:
            - "agent"
            - "-c"
            {{- if .Values.config.override.enabled }}
            - "/etc/jetstack-secure/agent/config/{{ default "config.yaml" .Values.config.override.configmap.key }}"
            {{- else }}
            - "/etc/jetstack-secure/agent/config/config.yaml"
            {{- end }}
            {{- if eq .Values.authentication.type "file" }}
            - "-k"
            - "/etc/jetstack-secure/agent/credentials/{{ default "credentials.json" .Values.authentication.secretKey}}"
            {{- end }}
            - "-p"
            - "0h1m0s"
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/jetstack-secure/agent/config"
              readOnly: true
            {{- if eq .Values.authentication.type "file" }}
            - name: credentials
              mountPath: "/etc/jetstack-secure/agent/credentials"
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.config.override.enabled }}
        - name: config
          configMap:
            name: {{ default "agent-config" .Values.config.override.configmap.name }}
            optional: false
        {{- else }}
        - name: config
          configMap:
            name: agent-config
            optional: false
        {{- end }}
        - name: credentials
          secret:
            secretName: {{ default "agent-credentials" .Values.authentication.secretName }}
            optional: false
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
