{{- if .Values.authentication.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentication.secretName}}
  labels:
    {{- include "jetstack-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ default "credentials.json" .Values.authentication.secretKey}}: {{ .Values.authentication.secretValue }}
{{- end -}}
