# Copyright 2024 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by the learn_kind_images.sh script in the makefile-modules repo.
# Do not edit manually.

kind_image_kindversion := v0.30.0

kind_image_kube_1.31_amd64 := docker.io/kindest/node:v1.31.12@sha256:9b0369c99755c4201e15618015138240182efd9cf2ba21351498d2e0176e8169
kind_image_kube_1.31_arm64 := docker.io/kindest/node:v1.31.12@sha256:55d14ffa8767b87ae715fbb154cf13a356e5871f2bea87532a2f911fcc5b0103
kind_image_kube_1.32_amd64 := docker.io/kindest/node:v1.32.8@sha256:284cc1c33c7170ea6cbfda225ad20484157c9781691c74451c4aaddf88d34114
kind_image_kube_1.32_arm64 := docker.io/kindest/node:v1.32.8@sha256:71488e3e22f1923d2f6508950a7e9121a3bcb7090e12779468f961cdc2974fc2
kind_image_kube_1.33_amd64 := docker.io/kindest/node:v1.33.4@sha256:59b665b0dc14d1fed52a9e172e4877bf00da1720aa2252128f91007544b0039d
kind_image_kube_1.33_arm64 := docker.io/kindest/node:v1.33.4@sha256:5e665c9be32ef55fb307e16a6a8e643602bafb01363f4b34d45fa55427ee03cf
kind_image_kube_1.34_amd64 := docker.io/kindest/node:v1.34.0@sha256:ede5bb6984830375d264e41b7169d03643f586d3e35316bf5229eaeb12bb18e0
kind_image_kube_1.34_arm64 := docker.io/kindest/node:v1.34.0@sha256:3229b411042d457a44ea8807e90520e4b7da8700a8617ed20f0c4cb799bebe2b

kind_image_latest_amd64 := $(kind_image_kube_1.34_amd64)
kind_image_latest_arm64 := $(kind_image_kube_1.34_arm64)
