apiVersion: v1
kind: ServiceAccount
metadata:
  name: venafi-components
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: venafi-components-create-token
rules:
- apiGroups: [ "" ]
  resources: [ "serviceaccounts/token" ]
  verbs: [ "create" ]
  resourceNames: [ "venafi-components" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: venafi-components-create-token
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: venafi-components-create-token
subjects:
- kind: ServiceAccount
  name: venafi-connection
  namespace: venafi
